require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/**/*

Style/Documentation:
  Enabled: false

Rails/LexicallyScopedActionFilter:
 Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*

Layout/LineLength:
  Exclude:
    - config/**/*

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
